#!/bin/sh

die() { printf '%s\n' "error: $*" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "${SCRIPT_DIR}/../vendor/getoptions.sh" # @inline getoptions

parser_definition() {
	setup   REST error:error help:usage -- \
		"Usage: custom-error [options...]" ''
	msg -- 'Options:'
	param   NUMBER --number validate:number         -- "accepts only a number"
	param   RANGE  --range  validate:'range 10 100' -- "accepts 10-100"
	disp    :usage -h --help
}

number() { case $OPTARG in (*[!0-9]*) return 1 ;; esac; }

range() {
	number || return 1
	[ "$1" -le "$OPTARG" ] && [ "$OPTARG" -le "$2" ] && return 0
	return 2
}

# Custom error handler
#   $1: default message  $2: error name  $3: option  $4+: context
error() {
	case $2 in
		unknown)  echo "Unrecognized option: $3" ;;
		number:*) echo "Not a number: $3" ;;
		range:1)  echo "Not a number: $3" ;;
		range:2)  echo "Out of range ($5-$6): $3"; return 2 ;;
		*) return 0 ;; # show default message
	esac
	return 1
}

eval "$(getoptions parser_definition - "$0") die 'failed to parse arguments'"

echo "NUMBER: $NUMBER"
echo "RANGE: $RANGE"
