#!/bin/sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "${SCRIPT_DIR}/../vendor/getoptions.sh" # @inline getoptions

die() { echo "error: $*" >&2; exit 1; }

parser_definition() {
	setup REST help:usage -- "Usage: trivial [options] [arguments]"
	msg -- 'Options:'
	disp :usage -h --help
}

eval "$(getoptions parser_definition parse)"
parse "$@"
eval "set -- $REST"

# --- Script Body ---
echo "Hello world!"
