#!/bin/sh

die() { printf '%s\n' "error: $*" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "${SCRIPT_DIR}/path/to/vendor/getoptions-3.3.2.sh" # @inline getoptions

parser_definition() {
	setup REST help:usage -- "Usage: trivial [options] [arguments]"
	msg -- 'Options:'
	disp :usage -h --help
}

eval "$(getoptions parser_definition - "$0") die 'failed to parse arguments'"

# --- Script Body ---
echo "Hello world!"
